# Valores default; podem ser sobrescritos por variáveis de ambiente LFSD_*

recipes_dir       = "/usr/share/lfsd/recipes"   # diretório de receitas
state_dir         = "/var/lib/lfsd"             # diretório de estado e manifests
stage_dir         = "/var/stage/lfsd"           # diretório de compilação/DESTDIR
cache_dir         = "/var/cache/lfsd"           # diretório base para bin e sources
bin_dir           = "/var/cache/lfsd/bin"       # pacotes binários empacotados
sources_dir       = "/var/cache/lfsd/sources"   # tarballs/git checkouts
log_dir           = "/var/log/lfsd"             # logs de transações
remote_url        = ""                           # URL do repo Git para sync
channel           = "stable"                     # canal de rolling release
snapshot_backend  = "btrfs"                      # "btrfs" ou "tar"
color             = "auto"                       # auto, always, never
jobs              = 0                            # 0 = autodetect cores
