# Valores default; variáveis LFSD_* sobrepõem.
recipes_dir = "/usr/share/lfsd/recipes"
state_dir   = "/var/lib/lfsd"
stage_dir   = "/var/stage/lfsd"
cache_dir   = "/var/cache/lfsd"
log_dir     = "/var/log/lfsd"recipes_dir = "/usr/share/lfsd/recipes"
state_dir = "/var/lib/lfsd"
stage_dir = "/var/stage/lfsd"
cache_dir = "/var/cache/lfsd"
bin_dir = "/var/cache/lfsd/bin"
sources_dir = "/var/cache/lfsd/sources"
log_dir = "/var/log/lfsd"
remote_url = "" # seu repo github aqui
channel = "stable"
snapshot_backend = "tar"
color = "auto"
jobs = 0
channel     = "stable"
snapshot_backend = "btrfs"  # ou "tar"
color = "auto"
